# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Thread-Pool
version:      0.31
version_from: lib/Thread/Pool.pm
installdirs:  site
requires:
    Thread::Conveyor:              0.15
    Thread::Conveyor::Monitored:   0.11

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
