--- #YAML:1.0
name:               Thread-Pool
version:            0.33
abstract:           group of threads for performing similar jobs
author:
    - Elizabeth Mattijsen (liz@dijkmat.nl)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Thread::Conveyor:     0.15
    Thread::Conveyor::Monitored:  0.11
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
